before_script:
  - python -V
  - make init
  - make setup

variables:
  CODECOV_TOKEN: ''
  PIPENV_VENV_IN_PROJECT: 1
  PIPENV_IGNORE_VIRTUALENVS: 1

stages:
  - test

python3.6:
  stage: test
  image: python:3.6
  script: pipenv run tox -v -e py36

python3.7:
  stage: test
  image: python:3.7
  script: pipenv run tox -v -e py37

after_script:
  - pipenv run codecov
